# Generated by Django 4.2.11 on 2024-06-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
    ]
