# Generated by Django 4.2.11 on 2024-04-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="accept_terms_and_conditions",
            field=models.BooleanField(default=False),
        ),
    ]
