# Generated by Django 5.0.7 on 2024-07-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(default='https://firebasestorage.googleapis.com/v0/b/web-project-ca895.appspot.com/o/haelsoft%2Fcourse2.png?alt=media&token=dc1bc361-eefb-4963-87b9-c449213f1ea0', max_length=255),
        ),
    ]
