# Generated by Django 5.0.7 on 2024-08-01 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='id',
        ),
        migrations.AddField(
            model_name='coursereview',
            name='coursereview_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
