# Generated by Django 5.1 on 2024-10-02 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_img_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default='7852d7d1-6da5-4106-8174-9a984b29492a', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category'),
            preserve_default=False,
        ),
    ]
