# Generated by Django 5.1 on 2024-08-30 11:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0002_alter_lesson_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
            ],
        ),
    ]
