# Generated by Django 5.1 on 2024-09-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0003_rename_userprogress_id_userprogress_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='userprogress_id',
        ),
    ]
