# Generated by Django 5.1 on 2024-09-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0005_alter_video_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='video_url',
            new_name='sample_video_url',
        ),
    ]
