# Generated by Django 5.1 on 2024-09-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0005_courseprogress_delete_userprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='description',
            new_name='transcript',
        ),
    ]
