# Generated by Django 5.1 on 2024-09-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0006_rename_video_url_lesson_sample_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
    ]
