# Generated by Django 5.1 on 2024-10-02 12:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0006_rename_description_lesson_transcript'),
        ('courses', '0008_course_img_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseProgress',
            new_name='UserCourseProgress',
        ),
    ]
