# Generated by Django 5.1 on 2024-09-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0008_courseprogress_remove_progress_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course_details.lesson'),
        ),
    ]
