# Generated by Django 5.1 on 2024-10-07 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0009_remove_usercourseprogress_completed_lessons_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.RemoveField(
            model_name='usercourseprogress',
            name='course',
        ),
    ]
