# Generated by Django 5.1 on 2024-10-21 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0010_alter_usercourseprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourseprogress',
            old_name='progress_id',
            new_name='id',
        ),
    ]
