# Generated by Django 5.1 on 2024-09-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0010_alter_video_duration_alter_video_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.FloatField(default=0.0, help_text='Duration in seconds'),
        ),
        migrations.DeleteModel(
            name='CourseProgress',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
