# Generated by Django 5.1 on 2024-09-28 18:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0012_lesson_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='sample_video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
