# Generated by Django 5.0.7 on 2024-08-15 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_coursereview_id_coursereview_coursereview_id'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transaction',
            name='courses',
            field=models.ManyToManyField(related_name='transactions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enrollment.transaction'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='course',
        ),
    ]
