# Generated by Django 5.1 on 2024-10-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_transaction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
