# Generated by Django 5.1 on 2024-09-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultationmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
